#!/bin/bash
pwd=$(pwd)
pwd=${pwd##*/}
cd ..
tree=$(tree -d -f -I "node_modules" ./${pwd} -tf --noreport -I '*~' --charset ascii $1 |
       sed -e 's/| \+/  /g' -e 's/[|`]-\+/ */g' -e 's:\(* \)\(\(.*/\)\([^/]\+\)\):\1[\4](\2):g')
printf "# Repositorio ${pwd} \n${tree}"
# Thanks to https://stackoverflow.com/users/487846/simon
printf "\n"
